version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: ticketeate_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.5.0
    container_name: ticketeate_grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - '3000:3000'
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.86.0
    container_name: ticketeate_otel_collector
    volumes:
      - ./otel/collector-config.yaml:/etc/otel-collector-config.yaml:ro
    command: ["--config", "/etc/otel-collector-config.yaml"]
    ports:
      - '4318:4318' # OTLP HTTP
      - '4317:4317' # OTLP gRPC
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.42
    container_name: ticketeate_jaeger
    ports:
      - '16686:16686' # Jaeger UI
      - '14268:14268' # Jaeger collector (HTTP)
    restart: unless-stopped

volumes:
  grafana-data:
